[project]
name = "macroforecast"
version = "0.1.0"
description = "Macroeconomic forecasting pipeline"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.34",
    "dt-ducklake-manager",
    "pandas>=2.3.3",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "s3fs>=0.4.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]

[tool.uv.sources]
dt-ducklake-manager = { git = "https://github.com/qbolliet/dt-ducklake-manager", rev = "v0.2.0" }
